### ISSUE TITLE
Using rollup with exif2css causes error: "[!] Error: 'default' is not exported by exif2css"

### ISSUE THREAD

**Issue by henryhsue** [demimonde/exif2css#2]
I am getting this error when trying to rollup exif2css into my project. 

I have a package A that uses package B that uses exif2css. Like so:

```
package_A:
  src/
  dist/
  node_modules/
  package_B: 
    src/
    dist/
    node_modules/
        exif2css/
```

My build process is usually to run:

```
1. cd package_B; yarn build #build the package_B dependency first, creating dist/
2. cd package_A; yarn build #build the package_A second, which depends on B. 
```

My problem is that the second command will break with the following output: 

```
yarn run v1.16.0
$ mkdir -p dist && rollup -c

src/index.js → dist/index.js, dist/index.es.js...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
created dist/index.js, dist/index.es.js in 4.6s

src/index.js → dist/browser.full-bundle.js...
[!] Error: 'default' is not exported by exif2css
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
react-file-utils/dist/index.es.js (27:0)
```

Here is the repository: https://github.com/henryhsue/selfiegoal/tree/rotation_issue

package_B is https://github.com/henryhsue/selfiegoal/tree/rotation_issue/app/react-activity-feed/react-file-utils
package_A is https://github.com/henryhsue/selfiegoal/tree/rotation_issue/app/react-activity-feed

and here is the commit showing how I am using exif2css: 

https://github.com/henryhsue/selfiegoal/commit/0db9f7bb54c031be0bcb84b08692119471b304a5

**Comment by zavr-1** [comment]
@henryhsue I don't know man, the `module` with the default field is published, it's not the package problem but rather the setup, maybe after you compiled your package B it looses the default export. The source is unavailable. The only thing I can suggest is to move exif2css up one directory because `node_modules` should actually work in a way such that scanning each dir up to the very root of the system, e.g.,
`import a from 'pckg'` from packageB should result it following 
- lookup ~/packageA/packageB/node_modules/pckg
- lookup ~/packageA/node_modules/pckg
- lookup ~/node_modules/pckg
- lookup /Users/node_modules/pckg
- lookup /node_modules/pckg

I don't know if rollup works like that but that's how Node.JS works. Also try `import e2c from 'exif2css/src'` but that would probably break your dev env...

**Comment by henryhsue** [comment]
Thanks, @zavr-1. That helped!
